[package]
name = "assignments-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.86"
learning-paths-tauri-react = { path = "../learning-paths-tauri-react/" }
serde = { version = "1", features = [ "derive" ] }
serde_yaml = "0.9.34"
