[package]
name = "lblp_assignments_plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
logic_based_learning_paths = { version = "0.0.1", path = "../logic_based_learning_paths/" }
serde = { version = "1", features = [ "derive" ] }
