#!/bin/sh
echo "running develop command";
nix develop --command bash -c "echo \"entering main project directory\" && cd rust-workspace/learning-paths-tauri-react && echo \"running tests\" && cargo test ";
