#!/bin/sh
# rebuilding the whole workspace so plugins are synced up with core
nix develop --command bash -c "echo \"entering main project directory\" && cd rust-workspace && cargo build --workspace --release && cd logic_based_learning_paths && echo \"running tests\" && cargo test ";
