name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Setup Rust Toolchain for GitHub CI
        uses: actions-rust-lang/setup-rust-toolchain@v1.9.0

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev graphviz

      - name: install Tarpaulin # for test coverage
        run: cargo install cargo-tarpaulin

      - name: run tests
        run: cd rust-workspace && cargo tarpaulin --all --out Html

      - name: upload coverage
        uses: actions/upload-artifact@v4
        with:
          path: rust-workspace/tarpaulin-report.html

  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Setup Rust Toolchain for GitHub CI
        uses: actions-rust-lang/setup-rust-toolchain@v1.9.0

      - name: install dependencies (Ubuntu)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

      - name: install Graphviz (cross-platform)
        uses: tlylt/install-graphviz@0a390a67cceaf17eb1ef1736c24c360249a6b9e9

      - name: install NPM packages
        run: npm install

      # note: does not build plugins!
      - uses: JonasKruckenberg/tauri-build@669b9aca35627e3d00721626aa543ca75cf49a13
        id: tauri_build


